### ISSUE TITLE
Draw only nth frame

### ISSUE THREAD

**Issue by Dene33** [iBrushC/animextras#1]
It would be great to have a feature to draw only nth frame. Right now every frame is drawn and it gets pretty messy sometimes. 

Also thank you so much for this awesome add-on, I was waiting something like that for a long time. Speed and performance are very important for onion skinning and this add-on doesn't drop my frame rate at all after few fast checks, good job!

**Comment by iBrushC** [comment]
Good evening,

That's actually something that's already included! If you select "per-frame
stepped" as the mode, you can choose a step value to use for the drawing
(you do have to update it when it's changed). This does what you're looking
for, and draws every "nth" frame! Thanks for contacting me, if you have any
other questions or suggestions I'd be happy to hear them.

Best wishes.
