### ISSUE TITLE
Update doesn't work after change in animation

### ISSUE THREAD

**Issue by Dene33** [iBrushC/animextras#3]
I have some animated character with rig, I create onion skinning for its mesh and draw the result. Everything works fine but if I change some bone rotation (and click `Update` button) - onion skinning is not updated.

**Comment by iBrushC** [comment]
This is because you need to keyframe it. Right now, there is no (efficient) way to get the exact state that a rigged object is in without having a keyframe, so you need to place one before updating.

**Comment by Dene33** [comment]
Actually I've keyframed it and it doesn't update.
