### ISSUE TITLE
It only works with one geometry at the same time.

### ISSUE THREAD

**Issue by lucianomunoz** [iBrushC/animextras#5]
If the character is composed of say 3 pieces it will only display for the last or "active" piece selected, if i pick a second geo and press update it will switch to that geo.

**Comment by iBrushC** [comment]
Only working with one geometry is something that I plan on changing, but not immediately. The update bug however is something that needs to be fixed. I'll get on that when I have time

**Comment by lucianomunoz** [comment]
Thanks man!, the addon is really promising and i love how simple and "ready to go" it is.
Hope all this feedback helps !

**Comment by iBrushC** [comment]
This bug has been fixed in version 1.0.3
