### ISSUE TITLE
Weird display when turning off overlays.

### ISSUE THREAD

**Issue by lucianomunoz** [iBrushC/animextras#6]
When you turn off overlays to just display the character and onion skin the onion skin gets sort of cut out by the character 
dont know how to paste a picture here to show it better.

**Comment by iBrushC** [comment]
If you could upload a screenshot to imgur and then link it that would help greatly.

**Comment by lucianomunoz** [comment]
oh yeah!
https://imgur.com/a/vnzwrM5
there you go, as you can see the character's sihlouette cuts out the onion skin.

**Comment by iBrushC** [comment]
This is probably due to a slow character motion, where a lot of keyframes are really close together. If you're looking to do a silhouette I'd recommend you stop drawing the onion skin first

**Comment by lucianomunoz** [comment]
no i dont want to do a sihlouette i just turned off "overlays" so it only shows the character and the onion skin but that's what happens, let me make a gif.

**Comment by lucianomunoz** [comment]
https://imgur.com/a/s90nBNQ

**Comment by iBrushC** [comment]
Update 1.0.3 now out, this should fix the issue
